version: 2.1

orbs:
  flutter: circleci/flutter@1.1

jobs:
  build_android:
    docker:
      - image: cimg/android:2023.08
    environment:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      FLUTTER_HOME: /home/circleci/flutter
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.19.0
      - run:
          name: Flutter doctor
          command: flutter doctor -v
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Flutter analyze
          command: flutter analyze
      - run:
          name: Run tests
          command: flutter test
      - run:
          name: Build APK
          command: flutter build apk --release --split-per-abi
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_android
